#!/usr/bin/env -S julia --project
# =============================================================================
# compute_continuous_shotnoise_diag.jl
#
# Build a DIAGONAL, ell-independent Poisson shot-noise matrix for the existing
# continuous SPHEREx tracer centers generated by generate_spherex_tracers_cont.jl.
#
# IMPORTANT
# ---------
# This script is intended as the immediate "reuse the existing Cl files" test.
# It does NOT regenerate tracers or PowerFull outputs.
#
# Existing tracer i:
#
#   phi_i(z_true) ∝ p(z_obs_i | z_true) × selection_s(z_true)
#
# is interpreted as the thin-observed-cell response at z_obs_i.  The centers
# are converted into finite, disjoint observed-z cells using midpoint edges in
#
#   u = ln(1 + z_obs).
#
# The expected angular count in cell i is approximated consistently with the
# existing point-centered kernel:
#
#   n_obs,s(z_obs_i)
#       = ∫ dz_true [dN_s/(dz_true dOmega)] p(z_obs_i | z_true)
#
#   Nbar_i
#       ≈ n_obs,s(z_obs_i) Δz_obs,i             [gal / sr]
#
# and the Poisson covariance is
#
#   N_ij = δ_ij / Nbar_i.                       [sr]
#
# The SIGNAL covariance C_ell^{ij} remains dense because the true-redshift
# kernels overlap.  Only the Poisson matrix is diagonal because the observed-z
# cells are disjoint catalog cells.
#
# No factor of 1/f_sky is included here.  dN/dz is per steradian, and f_sky
# belongs in the Fisher mode-count prefactor.
#
# Usage:
#
#   julia --project compute_continuous_shotnoise_diag.jl \
#       <spherex_params.h5> <tracer_meta_cont.h5> [Nshot_cont_diag.h5] \
#       [--nz-true=4096]
#
# If the output argument is omitted, the file is written next to the metadata:
#
#   Nshot_cont_diag.h5
#
# Required output datasets retained for the existing Fisher loader:
#
#   /N          [Ntracer × Ntracer]
#   /sample     [Ntracer]
#   /z_obs      [Ntracer]
#
# Additional diagnostics:
#
#   /cell_z_lo
#   /cell_z_hi
#   /cell_dz
#   /nobs_dz_sr
#   /Nbar_cell_sr
#   /nbar_eff
#   /tracer_paths
#   /provenance/...
# =============================================================================

using HDF5
using Dierckx
using Printf
using LinearAlgebra

# Must match the tracer generator.
const SURVEY_ZMIN = parse(Float64, get(ENV, "CONT_ZMIN", "0.05"))
const SURVEY_ZMAX = parse(Float64, get(ENV, "CONT_ZMAX", "4.6"))

gauss(x, μ, σ) =
    exp(-0.5 * ((x - μ) / σ)^2) / (sqrt(2π) * σ)

function trap_weights(x::AbstractVector{<:Real})
    n = length(x)
    n >= 2 || error("Need at least two integration points.")
    w = Vector{Float64}(undef, n)
    w[1] = 0.5 * (x[2] - x[1])
    w[end] = 0.5 * (x[end] - x[end-1])
    @inbounds for k in 2:n-1
        w[k] = 0.5 * (x[k+1] - x[k-1])
    end
    return w
end

function parse_args()
    opts = Dict{Symbol,Any}(
        :params  => nothing,
        :meta    => nothing,
        :out     => nothing,
        :nz_true => 4096,
    )

    positional = String[]
    for arg in ARGS
        if startswith(arg, "--nz-true=")
            opts[:nz_true] = parse(Int, split(arg, "=", limit=2)[2])
        elseif startswith(arg, "--")
            @warn "Unknown option ignored" arg
        else
            push!(positional, arg)
        end
    end

    length(positional) >= 2 || error(
        "Usage: compute_continuous_shotnoise_diag.jl " *
        "<params.h5> <tracer_meta_cont.h5> [Nshot_cont_diag.h5] " *
        "[--nz-true=4096]"
    )

    opts[:params] = abspath(positional[1])
    opts[:meta]   = abspath(positional[2])
    opts[:out] = length(positional) >= 3 ?
        abspath(positional[3]) :
        joinpath(dirname(opts[:meta]), "Nshot_cont_diag.h5")

    isfile(opts[:params]) || error("Parameter file not found: $(opts[:params])")
    isfile(opts[:meta])   || error("Tracer metadata file not found: $(opts[:meta])")
    opts[:nz_true] >= 256 || error("--nz-true should be at least 256")

    return opts
end

function sample_sigmaz_rel(f, sample::Int)::Float64
    if haskey(f, "sigmaz_$sample") && haskey(f, "zmid$sample")
        σz   = Float64.(read(f["sigmaz_$sample"]))
        zmid = Float64.(read(f["zmid$sample"]))
        length(σz) == length(zmid) ||
            error("sigmaz_$sample and zmid$sample lengths differ")
        rel = sort(σz ./ (1 .+ zmid))
        return rel[cld(length(rel), 2)]
    end

    canonical = (0.003, 0.01, 0.03, 0.10, 0.20)
    1 <= sample <= length(canonical) ||
        error("No sigma_z/(1+z) fallback for sample $sample")
    return canonical[sample]
end

function load_nbar_of_z(params_file::String, samples)
    out = Dict{Int,Tuple{Vector{Float64},Vector{Float64}}}()

    h5open(params_file, "r") do f
        ztest = Float64.(read(f["ztest"]))

        for s in samples
            if haskey(f, "shot_noise_d$s")
                inv_nbar = Float64.(read(f["shot_noise_d$s"]))
                length(inv_nbar) == length(ztest) ||
                    error(
                        "shot_noise_d$s length $(length(inv_nbar)) " *
                        "!= ztest length $(length(ztest))"
                    )

                nbar = Vector{Float64}(undef, length(inv_nbar))
                @inbounds for i in eachindex(inv_nbar)
                    iv = inv_nbar[i]
                    nbar[i] = isfinite(iv) && iv > 0 ? 1.0 / iv : 0.0
                end

                out[s] = (ztest, nbar)
                @info "sample $s: using z-dependent shot_noise_d$s as dN/dz/dOmega"

            elseif haskey(f, "sel_func_$(s)_com") &&
                   haskey(f, "shot_noise_$s")

                sel = Float64.(read(f["sel_func_$(s)_com"]))
                length(sel) == length(ztest) ||
                    error("sel_func_$(s)_com length mismatch")

                inv_total = Float64(read(f["shot_noise_$s"]))
                inv_total > 0 ||
                    error("shot_noise_$s must be positive")
                Nbar_total = 1.0 / inv_total

                wt = trap_weights(ztest)
                norm = sum(wt .* sel)
                norm > 0 ||
                    error("sel_func_$(s)_com has non-positive integral")

                nbar = Nbar_total .* sel ./ norm
                out[s] = (ztest, nbar)
                @warn(
                    "sample $s: shot_noise_d$s absent; using normalized " *
                    "sel_func_$(s)_com × scalar total count"
                )

            else
                error(
                    "sample $s lacks both shot_noise_d$s and " *
                    "(sel_func_$(s)_com + shot_noise_$s)"
                )
            end
        end
    end

    return out
end

function observed_cell_edges(
    zobs::AbstractVector{<:Real},
    zmin::Float64,
    zmax::Float64,
)
    n = length(zobs)
    n >= 2 || error("Need at least two observed-z centers per sample.")

    order = sortperm(zobs)
    zsort = Float64.(zobs[order])
    all(diff(zsort) .> 0) ||
        error("Observed-z centers must be unique and strictly increasing.")

    u = log1p.(zsort)
    umin = log1p(zmin)
    umax = log1p(zmax)

    # Midpoints between neighboring centers.
    uedge = Vector{Float64}(undef, n + 1)
    @inbounds for i in 1:n-1
        uedge[i+1] = 0.5 * (u[i] + u[i+1])
    end

    # Robust outer edges.  For the current tracer generator the first and last
    # centers equal zmin/zmax, giving half-width boundary cells.
    uedge[1] = max(umin, u[1] - 0.5 * (u[2] - u[1]))
    uedge[end] = min(umax, u[end] + 0.5 * (u[end] - u[end-1]))

    uedge[1] <= u[1] ||
        error("Lower cell edge exceeds first center.")
    uedge[end] >= u[end] ||
        error("Upper cell edge is below last center.")
    all(diff(uedge) .> 0) ||
        error("Constructed observed-cell edges are not increasing.")

    zedge = expm1.(uedge)
    zlo_sorted = zedge[1:end-1]
    zhi_sorted = zedge[2:end]
    dz_sorted  = zhi_sorted .- zlo_sorted

    invorder = invperm(order)
    return (
        zlo_sorted[invorder],
        zhi_sorted[invorder],
        dz_sorted[invorder],
    )
end

function main()
    opts = parse_args()

    @info "params=$(opts[:params])"
    @info "meta=$(opts[:meta])"
    @info "out=$(opts[:out])"
    @info "nz_true=$(opts[:nz_true])"
    @info "No 1/f_sky factor is applied to the shot noise."

    # -------------------------------------------------------------------------
    # Load existing tracer centers and ordering.
    # -------------------------------------------------------------------------
    sample_of, zobs_of, paths = h5open(opts[:meta], "r") do f
        haskey(f, "sample") || error("Metadata lacks /sample")
        haskey(f, "z_obs")  || error("Metadata lacks /z_obs")

        sample = Int.(read(f["sample"]))
        zobs   = Float64.(read(f["z_obs"]))
        tracer_paths = haskey(f, "tracer_paths") ?
            read(f["tracer_paths"]) :
            fill("", length(sample))

        return sample, zobs, tracer_paths
    end

    ntr = length(sample_of)
    length(zobs_of) == ntr ||
        error("sample and z_obs lengths differ")

    samples = sort(unique(sample_of))
    @printf(
        "Loaded %d existing continuous tracers across samples %s\n",
        ntr,
        string(samples),
    )

    # -------------------------------------------------------------------------
    # Recover the same survey range and sigma_z model used by the tracer maker.
    # -------------------------------------------------------------------------
    σrel_of_s = Dict{Int,Float64}()
    zmin = Inf
    zmax = -Inf

    h5open(opts[:params], "r") do f
        ztest   = Float64.(read(f["ztest"]))
        z_trunc = Float64.(read(f["z_trunc"]))

        zmin = max(SURVEY_ZMIN, ztest[1], z_trunc[1])
        zmax = min(SURVEY_ZMAX, ztest[end], z_trunc[end])

        for s in samples
            σrel_of_s[s] = sample_sigmaz_rel(f, s)
        end
    end

    zmin < zmax || error("Invalid survey range [$zmin,$zmax]")

    # -------------------------------------------------------------------------
    # Load true-z angular density and interpolate on a common integration grid.
    # -------------------------------------------------------------------------
    nbar_tab = load_nbar_of_z(opts[:params], samples)
    nbar_spl = Dict(
        s => Spline1D(nbar_tab[s][1], nbar_tab[s][2], k=3)
        for s in samples
    )

    ztrue = collect(range(zmin, zmax; length=opts[:nz_true]))
    wt = trap_weights(ztrue)

    nbar_true = Dict{Int,Vector{Float64}}()
    for s in samples
        nbar_true[s] = [
            max(Float64(nbar_spl[s](z)), 0.0)
            for z in ztrue
        ]
    end

    # -------------------------------------------------------------------------
    # Build disjoint observed-cell widths from the EXISTING centers.
    # -------------------------------------------------------------------------
    idx_of_sample = Dict(s => findall(==(s), sample_of) for s in samples)

    cell_z_lo = zeros(Float64, ntr)
    cell_z_hi = zeros(Float64, ntr)
    cell_dz   = zeros(Float64, ntr)

    for s in samples
        idx = idx_of_sample[s]
        lo, hi, dz = observed_cell_edges(zobs_of[idx], zmin, zmax)
        cell_z_lo[idx] .= lo
        cell_z_hi[idx] .= hi
        cell_dz[idx]   .= dz
    end

    # -------------------------------------------------------------------------
    # Thin-cell count associated with each existing point-centered tracer:
    #
    # nobs_i = ∫ dztrue nbar_true(ztrue) p(zobs_i | ztrue)
    # Nbar_i = nobs_i Δz_i
    # Nii    = 1/Nbar_i
    # -------------------------------------------------------------------------
    nobs_dz_sr  = zeros(Float64, ntr)
    Nbar_cell_sr = zeros(Float64, ntr)

    @info "Computing observed-z densities and finite-cell galaxy counts..."

    Threads.@threads for α in 1:ntr
        s = sample_of[α]
        zo = zobs_of[α]
        σrel = σrel_of_s[s]
        nb = nbar_true[s]

        acc = 0.0
        @inbounds @simd for k in eachindex(ztrue)
            zt = ztrue[k]
            σz = σrel * (1.0 + zt)
            acc += wt[k] * nb[k] * gauss(zo, zt, σz)
        end

        nobs_dz_sr[α] = acc
        Nbar_cell_sr[α] = acc * cell_dz[α]
    end

    all(isfinite.(Nbar_cell_sr)) ||
        error("Non-finite cell count encountered.")
    all(Nbar_cell_sr .> 0) ||
        error(
            "At least one observed-z cell has non-positive expected count. " *
            "Inspect the survey range and dN/dz."
        )

    # -------------------------------------------------------------------------
    # Diagonal Poisson covariance.
    # -------------------------------------------------------------------------
    Ndiag = 1.0 ./ Nbar_cell_sr
    N = Matrix(Diagonal(Ndiag))

    # -------------------------------------------------------------------------
    # Diagnostics.
    # -------------------------------------------------------------------------
    println("\nPer-sample diagnostics:")
    for s in samples
        idx = idx_of_sample[s]
        total_cells = sum(Nbar_cell_sr[idx])
        total_true  = sum(wt .* nbar_true[s])

        @printf(
            "  S%d: Ntr=%d, sigma_rel=%.5f, dz=[%.4e, %.4e], Nbar_cell=[%.4e, %.4e] gal/sr, Nii=[%.4e, %.4e] sr, sum_cells=%.6e gal/sr, int_true=%.6e gal/sr\n",
            s,
            length(idx),
            σrel_of_s[s],
            minimum(cell_dz[idx]),
            maximum(cell_dz[idx]),
            minimum(Nbar_cell_sr[idx]),
            maximum(Nbar_cell_sr[idx]),
            minimum(Ndiag[idx]),
            maximum(Ndiag[idx]),
            total_cells,
            total_true,
        )
    end

    offdiag_max = maximum(abs.(N .- Diagonal(diag(N))))
    @printf("\nMaximum absolute off-diagonal = %.3e\n", offdiag_max)
    offdiag_max == 0.0 ||
        error("Internal error: diagonal matrix has nonzero off-diagonal.")

    # -------------------------------------------------------------------------
    # Write in the layout expected by the existing Fisher loader.
    # -------------------------------------------------------------------------
    mkpath(dirname(opts[:out]))

    h5open(opts[:out], "w") do f
        f["N"]               = N
        f["sample"]          = sample_of
        f["z_obs"]           = zobs_of
        f["nbar_eff"]        = Nbar_cell_sr
        f["Nbar_cell_sr"]    = Nbar_cell_sr
        f["nobs_dz_sr"]      = nobs_dz_sr
        f["cell_z_lo"]       = cell_z_lo
        f["cell_z_hi"]       = cell_z_hi
        f["cell_dz"]         = cell_dz
        f["tracer_paths"]    = paths
        f["fsky"]            = 1.0

        create_group(f, "provenance")
        f["provenance/params"] = opts[:params]
        f["provenance/meta"] = opts[:meta]
        f["provenance/nz_true"] = opts[:nz_true]
        f["provenance/survey_zmin"] = zmin
        f["provenance/survey_zmax"] = zmax
        f["provenance/noise_model"] =
            "diagonal observed-z cell Poisson noise"
        f["provenance/count_approximation"] =
            "thin cell: Nbar_i = Delta_z_i * integral[nbar(z) p(zobs_i|z) dz]"
        f["provenance/fsky_applied_to_noise"] = 0

        for s in samples
            idx = idx_of_sample[s]
            f["provenance/sigmaz_rel_$s"] = σrel_of_s[s]
            f["provenance/Ntracer_$s"] = length(idx)
            f["provenance/Nbar_cells_sr_$s"] = sum(Nbar_cell_sr[idx])
            f["provenance/Nbar_true_sr_$s"] = sum(wt .* nbar_true[s])
        end
    end

    @printf(
        "\nWrote diagonal shot-noise matrix N[%d x %d] to:\n  %s\n",
        ntr,
        ntr,
        opts[:out],
    )

    println("\nNext step:")
    println("  Point the Fisher script's NSHOT_FILE at this file.")
    println("  Existing tracers and existing Cl files can be reused for this diagnostic.")
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end

